version: '3.9'

services:
  mongodb:
    image: "mongo"
    env_file:
      - ./env/mongo.env
    ports:
      - '27017:27017'
    container_name: mongodb
    volumes:
      - data:/data/db

  backend:
    build: ./backend
    image: goals-back-image
    env_file:
      - ./env/backend.env
    ports:
      - '80:80'
    container_name: goals-back-app
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    image: goals-front-image
    ports:
      - '3000:3000'
    container_name: goals-front-app
    stdin_open: true
    tty: true
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      - backend

volumes:
  data:
  logs:

