version: "3.9"

services:
  app:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    image: anchanto-image
    container_name: anchanto-app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
